// <auto-generated />
using System;
using HomeInbox_EngleanAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeInbox_EngleanAPI.Migrations
{
    [DbContext(typeof(DbDatacontext))]
    [Migration("20220721101402_AdjustNameTable")]
    partial class AdjustNameTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.TESTSCORE", b =>
                {
                    b.Property<Guid>("AGGREGATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AGGREGATEIDUSERPROFILE")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("NO")
                        .HasColumnType("int");

                    b.Property<int>("SCORE")
                        .HasColumnType("int");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.HasKey("AGGREGATEID");

                    b.HasIndex("AGGREGATEIDUSERPROFILE");

                    b.ToTable("TESTSCOREs");
                });

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.USER_LOGIN", b =>
                {
                    b.Property<Guid>("AGGREGATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AGGREGATEID");

                    b.ToTable("USER_LOGINs");
                });

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.USER_PROFILE", b =>
                {
                    b.Property<Guid>("AGGREGATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AGGREGATEIDUSERLOGIN")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.HasKey("AGGREGATEID");

                    b.HasIndex("AGGREGATEIDUSERLOGIN")
                        .IsUnique();

                    b.ToTable("USER_PROFILEs");
                });

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.VOCABULARY", b =>
                {
                    b.Property<Guid>("AGGREGATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MEANING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("VOCABULARYTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VOCABULARYs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AGGREGATEID");

                    b.ToTable("VOCABULARYs");
                });

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.TESTSCORE", b =>
                {
                    b.HasOne("HomeInbox_EngleanAPI.Database.DatabaseModel.USER_PROFILE", "UserProfile")
                        .WithMany("TESTSCOREs")
                        .HasForeignKey("AGGREGATEIDUSERPROFILE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.USER_PROFILE", b =>
                {
                    b.HasOne("HomeInbox_EngleanAPI.Database.DatabaseModel.USER_LOGIN", "userlogin")
                        .WithOne("UserProfile")
                        .HasForeignKey("HomeInbox_EngleanAPI.Database.DatabaseModel.USER_PROFILE", "AGGREGATEIDUSERLOGIN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userlogin");
                });

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.USER_LOGIN", b =>
                {
                    b.Navigation("UserProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.USER_PROFILE", b =>
                {
                    b.Navigation("TESTSCOREs");
                });
#pragma warning restore 612, 618
        }
    }
}
