// <auto-generated />
using System;
using HomeInbox_EngleanAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeInbox_EngleanAPI.Migrations
{
    [DbContext(typeof(DbDatacontext))]
    [Migration("20220708083904_CreateTableUserlogin")]
    partial class CreateTableUserlogin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.userlogin", b =>
                {
                    b.Property<Guid>("AGGREGATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AGGREGATEID");

                    b.ToTable("userlogins");
                });

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseModel.Vocabulary", b =>
                {
                    b.Property<Guid>("AGGREGATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MEANING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("VOCABULARY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VOCABULARYTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AGGREGATEID");

                    b.ToTable("vocabularies");
                });
#pragma warning restore 612, 618
        }
    }
}
