// <auto-generated />
using System;
using HomeInbox_EngleanAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeInbox_EngleanAPI.Migrations
{
    [DbContext(typeof(DbDatacontext))]
    partial class DbDatacontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HomeInbox_EngleanAPI.Database.DatabaseMdoel.Vocabulary", b =>
                {
                    b.Property<Guid>("AGGREGATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MEANING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VOCABULARY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VOCABULARYTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AGGREGATEID");

                    b.ToTable("vocabularies");
                });
#pragma warning restore 612, 618
        }
    }
}
